export const USER_SIGN_IN_START = 'USER_SIGN_IN_START';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED';

export const USER_SIGN_UP_START = 'USER_SIGN_UP_START';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILED = 'USER_SIGN_UP_FAILED';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const USER_LOGOUT = 'USER_LOGOUT';

export const MENU_HANDLE_QUANTITY = 'MENU_HANDLE_QUANTITY';
export const MENU_HIDE_QUANTITY_MODAL = 'MENU_HIDE_QUANTITY_MODAL';
