export const USER_SIGN_IN_START = 'USER_SIGN_IN_START';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED';

export const USER_SIGN_UP_START = 'USER_SIGN_UP_START';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILED = 'USER_SIGN_UP_FAILED';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const USER_LOGOUT = 'USER_LOGOUT';

export const CATERER_SIGN_IN_START = 'CATERER_SIGN_IN_START';
export const CATERER_SIGN_IN_SUCCESS = 'CATERER_SIGN_IN_SUCCESS';
export const CATERER_SIGN_IN_FAILED = 'CATERER_SIGN_IN_FAILED';

export const CATERER_SIGN_UP_START = 'CATERER_SIGN_UP_START';
export const CATERER_SIGN_UP_SUCCESS = 'CATERER_SIGN_UP_SUCCESS';
export const CATERER_SIGN_UP_FAILED = 'CATERER_SIGN_UP_FAILED';

export const CATERER_LOGOUT = 'CATERER_LOGOUT';

export const MENU_HANDLE_QUANTITY = 'MENU_HANDLE_QUANTITY';
export const MENU_HIDE_QUANTITY_MODAL = 'MENU_HIDE_QUANTITY_MODAL';

export const MENU_FETCH_MENUS_START = 'MENU_FETCH_MENUS_START';
export const MENU_FETCH_MENUS_SUCCESS = 'MENU_FETCH_MENUS_SUCCESS';
export const MENU_FETCH_MENUS_FAILED = 'MENU_FETCH_MENUS_FAILED';

export const MENU_FETCH_SINGLE_MENU_START = 'MENU_FETCH_SINGLE_MENU_START';
export const MENU_FETCH_SINGLE_MENU_SUCCESS = 'MENU_FETCH_SINGLE_MENU_SUCCESS';
export const MENU_FETCH_SINGLE_MENU_FAILED = 'MENU_FETCH_SINGLE_MENU_FAILED';

export const ORDER_ADD_TO_ORDERS_START = 'ORDER_ADD_TO_ORDERS_START';
export const ORDER_ADD_TO_ORDERS_SUCCESS = 'ORDER_ADD_TO_ORDERS_SUCCESS';
export const ORDER_ADD_TO_ORDERS_FAILED = 'ORDER_ADD_TO_ORDERS_FAILED';

export const SET_RES_CODE = 'SET_RES_CODE';
export const RESET_RES_CODE = 'RESET_RES_CODE';

export const ORDER_FETCH_USER_ORDERS_START = 'ORDER_FETCH_USER_ORDERS_START';
export const ORDER_FETCH_USER_ORDERS_SUCCESS = 'ORDER_FETCH_USER_ORDERS_SUCCESS';
export const ORDER_FETCH_USER_ORDERS_FAILED = 'ORDER_FETCH_USER_ORDERS_FAILED';

export const ORDER_INCREMENT_START = 'ORDER_INCREMENT_START';
export const ORDER_INCREMENT_SUCCESS = 'ORDER_INCREMENT_SUCCESS';
export const ORDER_INCREMENT_FAILED = 'ORDER_INCREMENT_FAILED';

export const ORDER_DECREMENT_START = 'ORDER_DECREMENT_START';
export const ORDER_DECREMENT_SUCCESS = 'ORDER_DECREMENT_SUCCESS';
export const ORDER_DECREMENT_FAILED = 'ORDER_DECREMENT_FAILED';

export const ORDER_DELETE_START = 'ORDER_DELETE_START';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAILED = 'ORDER_DELETE_FAILED';

export const MEAL_FETCH_MEALS_START = 'MEAL_FETCH_MEALS_START';
export const MEAL_FETCH_MEALS_SUCCESS = 'MEAL_FETCH_MEALS_SUCCESS';
export const MEAL_FETCH_MEALS_FAILED = 'MEAL_FETCH_MEALS_FAILED';

export const MEAL_TOGGLE_MODAL = 'MEAL_TOGGLE_MODAL';

export const MEAL_ADD_MEAL_START = 'MEAL_ADD_MEAL_START';
export const MEAL_ADD_MEAL_SUCCESS = 'MEAL_ADD_MEAL_SUCCESS';
export const MEAL_ADD_MEAL_FAILED = 'MEAL_ADD_MEAL_FAILED';

export const MEAL_DELETE_MEAL_START = 'MEAL_DELETE_MEAL_START';
export const MEAL_DELETE_MEAL_SUCCESS = 'MEAL_DELETE_MEAL_SUCCESS';
export const MEAL_DELETE_MEAL_FAILED = 'MEAL_DELETE_MEAL_FAILED';

export const MENU_ADD_MEALS_TO_MENU_START = 'MENU_ADD_MEALS_TO_MENU_START';
export const MENU_ADD_MEALS_TO_MENU_SUCCESS = 'MENU_ADD_MEALS_TO_MENU_SUCCESS';
export const MENU_ADD_MEALS_TO_MENU_FAILED = 'MENU_ADD_MEALS_TO_MENU_FAILED';