export const USER_SIGN_IN_START = 'USER_SIGN_IN_START';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED';

export const USER_SIGN_UP_START = 'USER_SIGN_UP_START';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILED = 'USER_SIGN_UP_FAILED';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const USER_LOGOUT = 'USER_LOGOUT';

export const CATERER_SIGN_IN_START = 'CATERER_SIGN_IN_START';
export const CATERER_SIGN_IN_SUCCESS = 'CATERER_SIGN_IN_SUCCESS';
export const CATERER_SIGN_IN_FAILED = 'CATERER_SIGN_IN_FAILED';

export const CATERER_SIGN_UP_START = 'CATERER_SIGN_UP_START';
export const CATERER_SIGN_UP_SUCCESS = 'CATERER_SIGN_UP_SUCCESS';
export const CATERER_SIGN_UP_FAILED = 'CATERER_SIGN_UP_FAILED';

export const CATERER_LOGOUT = 'CATERER_LOGOUT';

export const MENU_HANDLE_QUANTITY = 'MENU_HANDLE_QUANTITY';
export const MENU_HIDE_QUANTITY_MODAL = 'MENU_HIDE_QUANTITY_MODAL';

export const MENU_FETCH_MENUS_START = 'MENU_FETCH_MENUS_START';
export const MENU_FETCH_MENUS_SUCCESS = 'MENU_FETCH_MENUS_SUCCESS';
export const MENU_FETCH_MENUS_FAILED = 'MENU_FETCH_MENUS_FAILED';

export const ORDER_ADD_TO_ORDERS_START = 'ORDER_ADD_TO_ORDERS_START';
export const ORDER_ADD_TO_ORDERS_SUCCESS = 'ORDER_ADD_TO_ORDERS_SUCCESS';
export const ORDER_ADD_TO_ORDERS_FAILED = 'ORDER_ADD_TO_ORDERS_FAILED';

export const RESET_ORDER_RES_CODE = 'RESET_ORDER_RES_CODE';

export const ORDER_FETCH_USER_ORDERS_START = 'ORDER_FETCH_USER_ORDERS_START';
export const ORDER_FETCH_USER_ORDERS_SUCCESS = 'ORDER_FETCH_USER_ORDERS_SUCCESS';
export const ORDER_FETCH_USER_ORDERS_FAILED = 'ORDER_FETCH_USER_ORDERS_FAILED';

export const ORDER_INCREMENT_START = 'ORDER_INCREMENT_START';
export const ORDER_INCREMENT_SUCCESS = 'ORDER_INCREMENT_SUCCESS';
export const ORDER_INCREMENT_FAILED = 'ORDER_INCREMENT_FAILED';

export const ORDER_DECREMENT_START = 'ORDER_DECREMENT_START';
export const ORDER_DECREMENT_SUCCESS = 'ORDER_DECREMENT_SUCCESS';
export const ORDER_DECREMENT_FAILED = 'ORDER_DECREMENT_FAILED';

export const ORDER_DELETE_START = 'ORDER_DELETE_START';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAILED = 'ORDER_DELETE_FAILED';